# Generated by Django 4.0.4 on 2022-04-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='last_udpated_on',
            new_name='last_updated_on',
        ),
    ]
