# Generated by Django 4.0.4 on 2022-04-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0002_rename_last_udpated_on_library_last_updated_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='Books',
        ),
    ]
